### ISSUE TITLE
Punctuation

### ISSUE THREAD

**Issue by codeknight1** [obumnwabude/amigo#8] opened 2022-09-30 23:09 UTC
Full stop mark is not added at the end of the paragraph.

**Comment by sachinkrr02** [comment] 2022-10-15 03:38
May u please tell me where the problem is arising so that I can help you ?

**Comment by obumnwabude** [comment] 2022-10-21 09:29
Thanks @codeknight1 and @sachinkrr02

**Comment by obumnwabude** [comment] 2022-10-21 09:29
Close by #9

**Comment by obumnwabude** [comment] 2022-10-21 09:29
Closed by #9

**Closed by obumnwabude** 2022-10-21 09:29 UTC
